export const data = [
  {
    name: "images(1)",
    url: "/images/images(1).jpeg",
    description: "Photo 1 description",
    date: "2020-01-01",
    type: "image/jpeg",
  },
  {
    name: "images(2)",
    url: "/images/images(2).jpeg",
    description: "Photo 2 description",
    date: "2020-01-02",
    type: "image/jpeg",
  },
  {
    name: "images(3)",
    url: "/images/images(3).jpeg",
    description: "Photo 3 description",
    date: "2020-01-03",
    type: "image/jpeg",
  },
  {
    name: "images(4)",
    url: "/images/images(4).jpeg",
    description: "Photo 4 description",
    date: "2020-01-04",
    type: "image/jpeg",
  },
  {
    name: "images(5)",
    url: "/images/images(5).jpeg",
    description: "Photo 5 description",
    date: "2020-01-05",
    type: "image/jpeg",
  },
  {
    name: "images",
    url: "/images/images",
    description: "Photo 6 description",
    date: "2020-01-06",
    type: "image/jpeg",
  },
  {
    name: "download",
    url: "/images/download.jpeg",
    description: "Photo 7 description",
    date: "2020-01-07",
    type: "image/jpeg",
  },
  {
    name: "download(1)",
    url: "/images/download(1).jpeg",
    description: "Photo 8 description",
    date: "2020-01-08",
    type: "image/jpeg",
  },
  {
    name: "download(2)",
    url: "/images/download(2).jpeg",
    description: "Photo 9 description",
    date: "2020-01-09",
    type: "image/jpeg",
  },
];